source "https://rubygems.org"

gem "sinatra"
gem "activerecord"
gem "sinatra-activerecord"
gem "pg"
<? if( templateEngine == "haml" ){ ?>gem "haml"<? } ?>
gem "rake"
gem "sinatra-respond_to"

group :test, :development do
  gem "shotgun"
end
